_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.9.6
        t:
            "1":
                - 1
                - 2
                - 3
                - 50
                - 55
                - 77
            "2":
                - 1
                - 2
                - 3
                - 50
                - 55
                - 77
            "3":
                - 1
                - 15
                - 16
                - 23
                - 55
            "4": 3.9.6
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": darwin-arm64
callbacks:
    value:
        early_stopping: null
        lr_scheduler:
            kwargs:
                gamma: 0.9
                step_size: 10
            name: StepLR
            step: null
        model_checkpoint:
            k: 3
            metric_name: valEpoch/avg_epi_node_mcc
            minimize: false
            save_dir: /Users/mansoor/Documents/GSU/Projects/Antibody-Design/epitope-prediction/epitope-pred/asepcode/ckpts/20250104-150942
        model_checkpoint_edge:
            k: 3
            metric_name: valEpoch/avg_edge_index_bg_mcc
            minimize: false
            save_dir: /Users/mansoor/Documents/GSU/Projects/Antibody-Design/epitope-prediction/epitope-pred/asepcode/ckpts/edge/20250104-150942
dataset:
    value:
        ab:
            custom_embedding_method: null
            custom_embedding_method_src:
                method_name: null
                script_path: null
            embedding_model: esm2
        ag:
            custom_embedding_method: null
            custom_embedding_method_src:
                method_name: null
                script_path: null
            embedding_model: esm2
        name: asep
        node_feat_type: pre_cal
        root: ~/Documents/GSU/Projects/Antibody-Design/epitope-prediction/data
        split_idx: null
        split_method: null
hparams:
    value:
        act_list:
            - null
        batch_size: 32
        decoder:
            name: inner_prod
        dim_list:
            - 128
            - 64
        edge_cutoff: 0.5
        input_ab_act: relu
        input_ab_dim: 512
        input_ag_act: relu
        input_ag_dim: 480
        max_epochs: 30
        model_type: graph
        num_edge_cutoff: 3
        pos_weight: 100
        test_batch_size: 32
        train_batch_size: 32
        val_batch_size: 32
keep_interim_ckpts:
    value: true
logging_method:
    value: wandb
loss:
    value:
        edge_index_bg_rec_loss:
            kwargs:
                reduction: mean
                weight_tensor: 100
            name: edge_index_bg_rec_loss
            w: 1
        edge_index_bg_sum_loss:
            kwargs:
                thr: 40
            name: edge_index_bg_sum_loss
            w: 0.0003942821556421417
mode:
    value: train
num_threads:
    value: 4
optimizer:
    value:
        name: Adam
        params:
            lr: 0.001
            weight_decay: 0
seed:
    value: 3040969316
try_gpu:
    value: true
wandb_init:
    value:
        entity: mansoorbaloch931-georgia-state-university
        group: train
        job_type: train
        notes: pre_cal
        project: retrain-walle
        tags: pre_cal
work_dir:
    value: /Users/mansoor/Documents/GSU/Projects/Antibody-Design/epitope-prediction/epitope-pred/asepcode
